# Generated by Django 3.2.12 on 2023-09-12 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IjtimoiyNewModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_text', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Ijtimoiy Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='SiyosiyNewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_text', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'siyosiy yangiliklar',
            },
        ),
    ]
